### ISSUE TITLE
Typo in error message

### ISSUE THREAD

**Issue by ehmicky** [Cecilapp/netlify-plugin-cecil-cache#1]
The following error message is missing a closing `)` and is using single quotes instead of a template strings.

https://github.com/Cecilapp/netlify-plugin-cecil-cache/blob/1ce352c66a5aac1ce981840d4d6a8a6c9264c54a/index.js#L12

**Comment by ArnaudLigny** [comment]
Note to myself about "template strings": https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals.
