### ISSUE TITLE
Directory cache location

### ISSUE THREAD

**Issue by ehmicky** [Cecilapp/netlify-plugin-cecil-cache#2]
This issue is more a question about how Cecil works when it comes to caching.

The following line:

https://github.com/Cecilapp/netlify-plugin-cecil-cache/blob/1ce352c66a5aac1ce981840d4d6a8a6c9264c54a/index.js#L5

Assumes that the `.cache/` directory is always in the parent directory of the publish directory. This is not necessarily the project directory, since the publish directory might be under several subdirectories. I wanted to confirm whether this was the intended location?

**Comment by ArnaudLigny** [comment]
You are right: the location of the build directory and of the cache directory can be configured.

By default, the structure is:
[project]
|_ ...
|_ .cache (default cache directory)
|_ _site (default build directory)

I assuming a Netlify client use the default configuration. Could it be a problem?

**Comment by ehmicky** [comment]
For users who configure those directories, would there be a way to retrieve the custom location and use it instead?
For example, some plugins attempt to read the library's configuration file for this type of situation.

**Comment by ArnaudLigny** [comment]
I see but I don't know if I would have the courage to code a method of reading the configuration file in search of the cache folder (which is ultimately very rarely customized) or if it would be sufficient to add an "input" option configuration of the cache folder for the plugin.

**Comment by ehmicky** [comment]
Yes, that would work too :+1: 

Also, about the `.cache` directory, if the build directory is customized to `/some/sub/directory`, would the `.cache` directory be in the project root directory, or inside `/some/sub/directory/..`?

**Comment by ArnaudLigny** [comment]
> if the build directory is customized to /some/sub/directory, would the .cache directory be in the project root directory, or inside /some/sub/directory/..?

Good catch!

If the publish/build directory is customized, the cache directory stays in the project root.

So I should not use
```javascript
path.normalize(`${constants.PUBLISH_DIR}/../.cache`)
```
but just
```javascript
.cache
```
(or `inputs.cacheDir` if I implements input option)
?

**Comment by ehmicky** [comment]
Just `.cache` should work as a default value, since `process.cwd()` is the root directory. :+1: 
`path.normalize()` should not be required either.

An `inputs.cacheDir` would be nice too, since it would make this plugin work for users who customize the cache directory.
What do you think?

**Comment by ArnaudLigny** [comment]
Yes, thanks for the advice!

I will modify my code in this direction.

**Comment by ArnaudLigny** [comment]
I think it's now OK with in the last version, see https://github.com/Cecilapp/netlify-plugin-cecil-cache/blob/main/index.js#L5.

**Comment by ehmicky** [comment]
Thanks @Narno, this looks great!
