### ISSUE TITLE
Document UI-based installation method

### ISSUE THREAD

**Issue by ehmicky** [Cecilapp/netlify-plugin-cecil-cache#3]
The UI-based installation method is the preferred one since it is simpler for Netlify users.

Would it be possible to document it in the `README`? Thanks!
[Example of a plugin which documents it](https://github.com/bharathvaj-ganesan/netlify-plugin-airbrake#airbrake-netlify-build-plugin)

**Comment by ArnaudLigny** [comment]
Could I complete the readme file with the following?

## Usage

There are two ways to install this plugin on your application:

### Installing from Netlify UI

[One-click install](http://app.netlify.com/plugins/netlify-plugin-cecil-cache/install) to add this to your Cecil site.

### Installing with Netlify configuration file

Add the following lines to your project's `netlify.toml` file:

...

**Comment by ehmicky** [comment]
Yes, this sounds good!

**Comment by ArnaudLigny** [comment]
Ready with the PR #5 and could be applied after merging of https://github.com/netlify/plugins/pull/323.

**Comment by ehmicky** [comment]
Thanks @Narno!
